myp[tool.poetry]
name = "pythonproject4"
version = "0.1.0"
description = ""
authors = ["miplo <miplotnova@mail.ru>"]
readme = "README.tropmd"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
